[tools]
amazon-ecr-credential-helper = "latest"
argocd = "latest"
awscli = "latest"
bat = "latest"
bats = "latest"
bun = "latest"
chezmoi = "latest"
claude = "latest"
copilot-cli = "latest"
fd = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
helm = "latest"
herdr = "latest"
jq = "latest"
k9s = "latest"
kind = "latest"
kubectl = "latest"
kubectx = "latest"
kubens = "latest"
lazydocker = "latest"
lazygit = "latest"
minikube = "latest"
mkcert = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
pre-commit = "latest"
python = "latest"
rclone = "latest"
ripgrep = "latest"
rust = "latest"
shellcheck = "latest"
starship = "latest"
task = "latest"
usage = "latest"
uv = "latest"
worktrunk = "latest"
